
% // ==================== Test: XXZ spin chain ============================
% Hamiltonian [../SpinModel/IntrcMap_Folder/SpinModel_XXZtest.m]: 
%       H = sum_i Jxy(Sx_i Sx_i+1 + Sy_i Sy_i+1) + Jz Sz_i Sz_i+1 - h g
%       \mu_b S_i^z
% Fitting Data [../ExpData] 
% (generated by iLTRG with Jxy = 1 Kelvin, Jz = 1.5 Kelvin, gxy = gz = 2): 
%       specific heat (0 Tesla, 1 Tesla, 2 Tesla)
%       susceptibility (0.1 Tesls, under x and z direction)
% Bayesian optimization parameters [ImportBOPara.m]
% Many-body solver parameters [ImportMBSolverPara.m]
% =========================================================================
% QMagen Collaboration: YG.BUAA & WL.ITP, 2021-08-29

clear; clc;
maxNumCompThreads(4);
addpath(genpath('../ManyBodySolver/'));
addpath(genpath('../SpinModel/'));
addpath(genpath('../svd_lapack_interface/'));
addpath('../UtilityFunc/')
% addpath('./ObsFunction/')
% set model
Para.IntrcMap_Name = 'IntrcMap_TLARX';

% set coupling strength
% Para.Model.J1xy = 0.066215;%0.591976456834176;
% Para.Model.J1z = 0.0044152;
% Para.Model.JPD = 0.010365;
% Para.Model.JGamma = 0.01846;

ParaJ = [0.049839    -0.0019547    0.019584    0.010731    2.1547];
% ParaJ = [0.031495    0.0049493    -0.024494    0.02323    2.215];
Para.Model.J1xy = ParaJ(1);%0.591976456834176;
Para.Model.J1z = ParaJ(2);
Para.Model.JPD = ParaJ(3);
Para.Model.JGamma = ParaJ(4);

Para.Model.J2xy = 0;
Para.Model.J2z = 0;
Para.Model.Dz = 0;
Para.d = 2;

% set lattice geometry
Para.Geo.L = 12;
Para.Geo.Lx = 4;
Para.Geo.BCX = 'OBC';
Para.Geo.Ly = 3;
Para.Geo.BCY = 'PBC';
Para.L = Para.Geo.L;

% set magnetic field
Para.Model.ES = 1;
[ UnitCon ] = GetUnitCon(Para);
Para.g_fec.g = [2.29388644401928, 2, ParaJ(end)];
Para.g_fec.dir{1} = [1,0,0];
Para.g_fec.dir{2} = [0,1,0];
Para.g_fec.dir{3} = [0,0,1];
%
Para.Field.h = [0,0,0]/UnitCon.h_con;
Para.Field.hdir = Para.Field.h / norm(Para.Field.h);
Para.Field.h = norm(Para.Field.h);
Para.ThDQ = 'Cm';
Para.ManyBodySolver = 'ED';
Para.fileID = 1;
Para = ImportMBSolverPara(Para);
Rslt_0T = GetEDRslt(Para);
Rslt_0T.H = [];

Para.Field.h = [0,0,0.05]/UnitCon.h_con;
Para.Field.hdir = Para.Field.h / norm(Para.Field.h);
Para.Field.h = norm(Para.Field.h);
Para.ThDQ = 'Cm';
Para.ManyBodySolver = 'ED';
Para.fileID = 1;
Para = ImportMBSolverPara(Para);
Rslt_0p05T = GetEDRslt(Para);
Rslt_0p05T.H = [];

Para.Field.h = [0,0,0.1]/UnitCon.h_con;
Para.Field.hdir = Para.Field.h / norm(Para.Field.h);
Para.Field.h = norm(Para.Field.h);
Para.ThDQ = 'Cm';
Para.ManyBodySolver = 'ED';
Para.fileID = 1;
Para = ImportMBSolverPara(Para);
Rslt_0p1T = GetEDRslt(Para);
Rslt_0p1T.H = [];

save('ExpData/MBRslt/Rslt_p.mat', 'Rslt_0T', 'Rslt_0p05T', 'Rslt_0p1T', 'ParaJ');