
% // ==================== Test: XXZ spin chain ============================
% Hamiltonian [../SpinModel/IntrcMap_Folder/SpinModel_XXZtest.m]: 
%       H = sum_i Jxy(Sx_i Sx_i+1 + Sy_i Sy_i+1) + Jz Sz_i Sz_i+1 - h g
%       \mu_b S_i^z
% Fitting Data [../ExpData] 
% (generated by iLTRG with Jxy = 1 Kelvin, Jz = 1.5 Kelvin, gxy = gz = 2): 
%       specific heat (0 Tesla, 1 Tesla, 2 Tesla)
%       susceptibility (0.1 Tesls, under x and z direction)
% Bayesian optimization parameters [ImportBOPara.m]
% Many-body solver parameters [ImportMBSolverPara.m]
% =========================================================================
% QMagen Collaboration: YG.BUAA & WL.ITP, 2021-08-29

clear; clc;
maxNumCompThreads(4);
addpath(genpath('../ManyBodySolver/TensorFunction'));
addpath(genpath('../ManyBodySolver/CBEtanTRG'));
addpath(genpath('../ManyBodySolver/ED'));
addpath(genpath('../SpinModel/'));
addpath(genpath('../svd_lapack_interface/'));
addpath('./ObsFunction/')
% set model
Para.IntrcMap_Name = 'IntrcMap_DeltaChain';

% set coupling strength
Para.Lx = 256;

Para.d = 2;

% set lattice geometry
Para.L = Para.Lx;

% set magnetic field
Para.h = [0,0,0];
Para.Field.h = [0,0,0];
Para.Model.J1xy = 1;
Para.Model.J1z = 1;
Para.Model.J2xy = 0.5;
Para.Model.J2z = 0.5;
%
Para.ThDQ = 'Cm';
Para.ManyBodySolver = 'DMRG';
Para.fileID = 1;
Para = ImportMBSolverPara(Para);

switch Para.ManyBodySolver
    case 'XTRG'
        Rslt = GetXTRGRslt(Para);
    case 'ED'
        Rslt = GetEDRslt(Para);
    case 'TSRG'
        Rslt = GetTSRGRslt(Para);
    case 'DMRG'
        addpath(genpath('../ManyBodySolver/DMRG/'))
        Rslt = GetDMRGRslt(Para);
    case 'CBEtanTRG'
        Rslt = GetCBEtanTRGRslt(Para);
end
